sudo: required
dist: trusty
language: python
python:
  - "3.5.2"
  - "3.6"
addons:
  firefox: "49.0"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - make webdriver
  - make test
